'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const root = path.join(__dirname, '..', 'src');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const renderer = fs.readFileSync(path.join(root, 'renderer.js'), 'utf8');
const main = fs.readFileSync(path.join(root, 'main.js'), 'utf8');
const preload = fs.readFileSync(path.join(root, 'preload.js'), 'utf8');

assert.match(html, /id="accountLoginDocument"/);
assert.match(html, /id="accountLoginCodeButton"[^>]*>Entrar com código</);
assert.match(html, /id="accountLoginCode"[^>]*autocomplete="one-time-code"/);
assert.match(html, /id="accountLoginCodeConfirmButton"/);
assert.match(html, /id="licenseEmailCodeModal"/);
assert.match(html, /id="licenseEmailCodeInput"[^>]*autocomplete="one-time-code"/);
assert.doesNotMatch(html, /id="devicesDocumentInput"|id="devicesLoginButton"/);
assert.match(html, /id="devicesAccountEmail"/);
assert.match(renderer, /performAccountLogin\(email, document\)/);
assert.match(renderer, /performAccountCodeLogin\(email, challengeId, code\)/);
assert.match(renderer, /requestLicenseLoginCode\(\{ email \}\)/);
assert.match(renderer, /verifyLicenseLoginCode\(\{/);
assert.match(renderer, /runEmailVerifiedLicenseAction/);
assert.match(renderer, /removeLicenseDevice\(\{ machineId, \.\.\.verification \}\)/);
assert.match(renderer, /!\[11, 14\]\.includes\(cleanDocument\.length\)/);
assert.doesNotMatch(renderer, /devicesDocumentInput|devicesLoginButton/);
assert.match(preload, /requestLicenseLoginCode:.*request-license-login-code/);
assert.match(preload, /verifyLicenseLoginCode:.*verify-license-login-code/);
assert.match(main, /async function requestLicenseLoginCode/);
assert.match(main, /async function verifyLicenseLoginCode/);
assert.match(main, /persistLicenseDeviceLogin/);
assert.match(main, /result\.document \|\| result\.cpf \|\| result\.cnpj/);
assert.match(main, /const hasStoredLogin = Boolean\(storedDeviceLoginEmail \|\| license\.email\)/);
assert.match(main, /const deviceLoggedIn = !explicitlyLoggedOut && hasStoredLogin/);
assert.doesNotMatch(main, /accountSessionToken|ensureStoredAccountSession/);
const activationStart = main.indexOf("ipcMain.handle('activate-license'");
const activationEnd = main.indexOf('function prepareForAppQuit', activationStart);
assert.notEqual(activationStart, -1);
assert.notEqual(activationEnd, -1);
assert.doesNotMatch(main.slice(activationStart, activationEnd), /verificationCode|challengeId/);
const removalStart = main.indexOf('async function removeLicenseDevice');
const removalEnd = main.indexOf('const LICENSE_SHARD_FILES', removalStart);
assert.notEqual(removalStart, -1);
assert.notEqual(removalEnd, -1);
const removal = main.slice(removalStart, removalEnd);
assert.match(removal, /challengeId:String\(request\.challengeId \|\| ''\)/);
assert.match(removal, /verificationCode:String\(request\.verificationCode \|\| ''\)/);
assert.match(removal, /result\.verificationRequired === true/);
assert.match(removal, /result\.document \|\| result\.cpf \|\| result\.cnpj/);
assert.doesNotMatch(removal, /if \(!loginDocument\.cpf && !loginDocument\.cnpj\) throw/);

const formatterStart = renderer.indexOf('function loginDocumentDigits');
const formatterEnd = renderer.indexOf('function setupLoginDocumentInput', formatterStart);
assert.notEqual(formatterStart, -1);
assert.notEqual(formatterEnd, -1);
const formatterContext = {};
vm.runInNewContext(`${renderer.slice(formatterStart, formatterEnd)}\nthis.formatLoginDocument = formatLoginDocument;`, formatterContext);
assert.equal(formatterContext.formatLoginDocument('07843249567'), '078.432.495-67');
assert.equal(formatterContext.formatLoginDocument('04252011000110'), '04.252.011/0001-10');

console.log('HOOK_CENTER_ACCOUNT_AUTH_OK: login novo usa CPF/CNPJ; contas antigas removem dispositivos com confirmação por código.');
