assert(AudioDestinationSpace.needsWarning(availableBytes: 0))
assert(AudioDestinationSpace.needsWarning(availableBytes: 4_999_999_999))
assert(!AudioDestinationSpace.needsWarning(availableBytes: 5_000_000_000))
assert(!AudioDestinationSpace.needsWarning(availableBytes: 8_000_000_000))
assert(!AudioDestinationSpace.needsWarning(availableBytes: -1))
let base = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
try FileManager.default.createDirectory(at: base, withIntermediateDirectories: true)
defer { try? FileManager.default.removeItem(at: base) }
let missing = base.appendingPathComponent("new/export/stems")
assert(AudioDestinationSpace.existingAncestor(of: missing) == base.resolvingSymlinksInPath())
let link = base.appendingPathComponent("linked")
try FileManager.default.createSymbolicLink(at: link, withDestinationURL: base)
assert(AudioDestinationSpace.existingAncestor(of: link.appendingPathComponent("recordings")) == base.resolvingSymlinksInPath())
assert(AudioDestinationSpace.availableBytes(at: missing) != nil)
assert(!FileManager.default.fileExists(atPath: missing.path))
print("DESTINATION_DISK_PREFLIGHT_BOUNDARY_AND_SYMLINK_OK")
