let source = UUID(), hovered = UUID(), groupEnd = UUID(), other = UUID()
let state = TrackReorderState()
state.begin(track: source)
state.indicate(hovered, after: true, joinsGroup: true)
precondition(state.joinsGroup && state.target == hovered)
state.indicate(groupEnd, after: true, joinsGroup: false, hoveredTrack: hovered)
precondition(!state.joinsGroup && state.target == groupEnd && state.hoveredTrack == hovered)
state.leave(hovered)
precondition(state.target == nil && state.active, "leaving the hit row clears a line drawn at the distant group boundary")
state.indicate(groupEnd, after: true, joinsGroup: false, hoveredTrack: other)
state.leave(hovered)
precondition(state.target == groupEnd, "a late exit from an old row does not erase a new preview")
state.reject(other)
precondition(state.target == nil && state.blockedTarget == other)
state.finish()
precondition(state.target == nil && state.blockedTarget == nil && state.hoveredTrack == nil && !state.active)
print("TRACK_DROP_INDICATOR_OK")
