// Generated by scripts/sync-import-rules.py from Hook Center.
import Foundation
enum HookImportRules {
static let source = #"""

const path = {
 basename(value, extension = '') { const name = String(value).split('/').pop(); return extension && name.endsWith(extension) ? name.slice(0, -extension.length) : name; },
 extname(value) { const name = this.basename(value); const dot = name.lastIndexOf('.'); return dot > 0 ? name.slice(dot) : ''; },
 resolve(value) { return value; }, join(...values) { return values.join('/'); }
};
const crypto = { randomInt(max) { return Math.floor(Math.random() * max); } };
const SUPPORTED_AUDIO_EXTENSIONS = new Set(['.wav', '.wave', '.aif', '.aiff', '.mp3']);
const CREATE_PROJECT_REGION_GAP_SECONDS = 30;
const CREATE_PROJECT_INTERNAL_PEAK_DB = -1;
const CREATE_PROJECT_DESTINATION_EXISTS_MESSAGE = 'Não é possível criar este projeto. Já existe outro projeto com esse nome nessa pasta.';
const CREATE_PROJECT_TRACK_RULES = [
  { name: 'Click', pattern: /\b(click|metronomo|metronome)\b/ },
  { name: 'Regência', pattern: /\b(regencia|maestro|gps|contagem|count in|countin)\b/ },
  { name: 'Backing Vocal', pattern: /\b(back(?:ing)?(?: vocals?| vocais| vozes?| voz)?|backs?|bk|bgv)\b/ },
  // O nome da pista pode vir acompanhado pelo título da música, pelo artista
  // ou por uma seção. A correspondência deve funcionar em qualquer parte
  // do nome, assim como já acontece com as demais pistas.
  { name: 'Vox Synth', pattern: /\b(synth vox|syn ?vox|air vox|space voices?|vocal airy|vox synth|d ?50 voices?|vocal oohz|spaced voxx?|wavox)\b/ },
  { name: 'Vocal', pattern: /\bvocals?\b/ },
  { name: 'Vox', pattern: /\bvox\b/ },
  { name: 'Guia', pattern: /\b(guia|guide|voz|vz)\b/ },
  { name: 'Sanfona', pattern: /\b(sanfona|acordeon|accordion)\b/ },
  { name: 'Ukulele', pattern: /\b(ukulele|ukelele|uke)\b/ },
  { name: 'Cavaquinho', pattern: /\b(cavaquinho|cavaquinhos|cavaco|cavacos)\b/ },
  { name: 'Banjo', pattern: /\b(banjo|banjos)\b/ },
  { name: 'Bandolim', pattern: /\b(bandolim|bandolins|mandolin|mandolins)\b/ },
  { name: 'Violão Nylon', pattern: /\b(vl nylon|violao nylon|nylon guitar|nylon)\b/ },
  { name: 'Violão', pattern: /\b(violao|acoustic guitar|acoustic)\b/ },
  { name: 'Guitarra', pattern: /\b(guitarras?|guitars?|gtr|guita|guit)\b/ },
  { name: 'Baixo', pattern: /\b(baixo|bass)\b/ },
  { name: 'Bumbo', pattern: /\b(bumbos?|kicks?|bass drums?|gran cassa|bd)\b/ },
  { name: 'Caixa', pattern: /\b(caixas?|snares?|cx)\b/ },
  { name: 'Hi-Hat', pattern: /\b(hi ?hats?|hihats?|chimbal|chimbais|chimbaus?|ximbal|ximbais|ximbaus?|hh)\b/ },
  { name: 'Surdo', pattern: /\b(surdos?|sd|floor ?toms?)\b/ },
  { name: 'Tom', pattern: /\b(tom ?toms?|tomtoms?|tontons?|rontons?|toms?)\b/ },
  { name: 'Over', pattern: /\b(overs?|overheads?|ohs?)\b/ },
  { name: 'Ride', pattern: /\b(rides?)\b/ },
  { name: 'Crash', pattern: /\b(crash(?:es)?)\b/ },
  { name: 'Reverse Cymbal', pattern: /\b(reverse cymbals?|rev cymbals?|revcymbl)\b/ },
  { name: 'Pratos', pattern: /\b(prato|pratos|cymbals?|cymbs?|cym)\b/ },
  { name: 'Conga', pattern: /\b(congas?|tumbadoras?|cg)\b/ },
  { name: 'Bongo', pattern: /\b(bongos?|bg)\b/ },
  { name: 'Timbal', pattern: /\b(timbal|timbau|timbales?)\b/ },
  { name: 'Repique de Mão', pattern: /\b(repique de mao|hand repique)\b/ },
  { name: 'Repique', pattern: /\b(repique|repinique|repiniques?)\b/ },
  { name: 'Meia Lua', pattern: /\b(meia lua|half moon(?: tambourine)?)\b/ },
  { name: 'Pandeiro', pattern: /\b(pandeiro|pandeiros|tambourine|tambourines)\b/ },
  { name: 'Pandeirola', pattern: /\b(pandeirola|pandeirolas)\b/ },
  { name: 'Bacurinha', pattern: /\b(bacurinha|bacurinhas)\b/ },
  { name: 'Tamborim', pattern: /\b(tamborim|tamborins)\b/ },
  { name: 'Shaker', pattern: /\b(shaker|shakers)\b/ },
  { name: 'Ganzá', pattern: /\b(ganza|ganzas)\b/ },
  { name: 'Agogô', pattern: /\b(agogo|agogos|sambago bells?)\b/ },
  { name: 'Cowbell', pattern: /\b(cowbell|cowbells|cow bell|cow bells)\b/ },
  { name: 'Clave', pattern: /\b(clave|claves)\b/ },
  { name: 'Triângulo', pattern: /\b(triangulo|triangle)\b/ },
  { name: 'Cajón', pattern: /\b(cajon|cajons)\b/ },
  { name: 'Djembe', pattern: /\b(djembe|djembes)\b/ },
  { name: 'Darbuka', pattern: /\b(darbuka|darabuka|doumbek)\b/ },
  { name: 'Cabasa', pattern: /\b(cabasa|cabassa)\b/ },
  { name: 'Maracas', pattern: /\b(maraca|maracas)\b/ },
  { name: 'Chocalho', pattern: /\b(chocalhos?|rattles?|jingle bells?|sleigh bells?)\b/ },
  { name: 'Cuíca', pattern: /\b(cuica|cuicas)\b/ },
  { name: 'Berimbau', pattern: /\b(berimbau|berimbaus)\b/ },
  { name: 'Caxixi', pattern: /\b(caxixi|caxixis)\b/ },
  { name: 'Reco-Reco', pattern: /\b(reco reco|recoreco|guiros?|gueros?|guiras?)\b/ },
  { name: 'Afoxé', pattern: /\b(afoxe|afoxes)\b/ },
  { name: 'Alfaia', pattern: /\b(alfaia|alfaias)\b/ },
  { name: 'Zabumba', pattern: /\b(zabumba|zabumbas)\b/ },
  { name: 'Atabaque', pattern: /\b(atabaque|atabaques)\b/ },
  { name: 'Tantã', pattern: /\b(tanta|tantan|tan tan)\b/ },
  { name: 'Rebolo', pattern: /\b(rebolo|rebolos)\b/ },
  { name: 'Sopapo', pattern: /\b(sopapo|sopapos)\b/ },
  { name: 'Tarol', pattern: /\b(tarol|tarols)\b/ },
  { name: 'Xequerê', pattern: /\b(xequeres?|shekeres?|chequeres?)\b/ },
  { name: 'Rocar', pattern: /\b(rocar|rocar)\b/ },
  { name: 'Palmas', pattern: /\b(palmas|hand clap|handclap|claps?)\b/ },
  { name: 'Snap', pattern: /\b(finger snap|snap|snaps)\b/ },
  { name: 'Rimshot', pattern: /\b(rimshot|rim shot|rim)\b/ },
  { name: 'Tímpano', pattern: /\b(timpano|timpani|kettle drum)\b/ },
  { name: 'Tabla', pattern: /\b(tabla|tablas)\b/ },
  { name: 'Taiko', pattern: /\b(taikos?|taiko drums?|wadaiko)\b/ },
  { name: 'Tambora', pattern: /\b(tamboras?|dominican drums?)\b/ },
  { name: 'Bodhrán', pattern: /\b(bodhran|bodhrans)\b/ },
  { name: 'Frame Drum', pattern: /\b(frame drums?|tambores? de moldura)\b/ },
  { name: 'Talking Drum', pattern: /\b(talking drums?)\b/ },
  { name: 'Gong', pattern: /\b(gong|gongs)\b/ },
  { name: 'Jamblock', pattern: /\b(jam ?blocks?|jamblocks?)\b/ },
  { name: 'Bloco', pattern: /\b(blast blocks?|granite blocks?|temple blocks?|blocks? de percussao)\b/ },
  { name: 'Woodblock', pattern: /\b(woodblock|wood block|wood blocks)\b/ },
  { name: 'Bar Chimes', pattern: /\b(bar chimes?|mark trees?|wind chimes?)\b/ },
  { name: 'Bell Tree', pattern: /\b(bell trees?)\b/ },
  { name: 'Waterfall', pattern: /\b(percussion waterfalls?|waterfall percussion|waterfalls?)\b/ },
  { name: 'Vibraslap', pattern: /\b(vibraslap|vibra slap)\b/ },
  { name: 'Castanholas', pattern: /\b(castanholas?|castanets?)\b/ },
  { name: 'Apito', pattern: /\b(apito|apitos|whistle|whistles)\b/ },
  { name: 'Udu', pattern: /\b(udu|udus)\b/ },
  { name: 'Marimba', pattern: /\b(marimba|marimbas)\b/ },
  { name: 'Vibrafone', pattern: /\b(vibrafone|vibraphone|vibes)\b/ },
  { name: 'Xilofone', pattern: /\b(xilofone|xylophone)\b/ },
  { name: 'Kalimba', pattern: /\b(kalimba|kalimbas)\b/ },
  { name: 'Steel Pan', pattern: /\b(steel pan|steelpan|steel drum)\b/ },
  { name: 'Handpan', pattern: /\b(handpan|handpans|hang drum)\b/ },
  { name: 'Bateria', pattern: /\b(baterias?|bateras?|drums?|drum ?kits?|drum ?sets?|drumsets?|kit de bateria|(?:606|707|808|909) ?kits?|linndrum|drum machine)\b/ },
  { name: 'Rhodes', pattern: /\b(rhodes|rhode)\b/ },
  { name: 'Wurlitzer', pattern: /\b(wurlitzer|wurli|wurly)\b/ },
  { name: 'Electric Piano', pattern: /\b(electric piano|e piano|ep)\b/ },
  { name: 'CP80', pattern: /\b(cp ?80)\b/ },
  { name: 'DX', pattern: /\b(dx(?: ?(?:1|5|7|9|11|21|27|100))?|dx (?:piano|ep|e piano|keys?|synth)|fm (?:piano|ep|e piano|keys?)|tx ?816)\b/ },
  { name: 'Honky Tonk', pattern: /\b(honky tonk|honkytonk)\b/ },
  { name: 'Clavi', pattern: /\b(clavinet|clavi|clav)\b/ },
  { name: 'Hammond', pattern: /\b(hammond|b ?3 organ|b ?3)\b/ },
  { name: 'Piano', pattern: /\b(piano|pno)\b/ },
  { name: 'Órgão', pattern: /\b(orgao|organ|orgn)\b/ },
  { name: 'Cravo', pattern: /\b(cravo|harpsichord|harpsi)\b/ },
  { name: 'Celesta', pattern: /\b(celesta|celeste)\b/ },
  { name: 'Glockenspiel', pattern: /\b(glockenspiel|glock)\b/ },
  { name: 'Music Box', pattern: /\b(music box|caixinha de musica)\b/ },
  { name: 'Bells', pattern: /\b(bell|bells|sino|sinos)\b/ },
  { name: 'Mallet', pattern: /\b(mallet|mallets)\b/ },
  { name: 'Synth Brass', pattern: /\b(synth brass|syn brass|synthbrass|syn ?brss|syn ?brs|sy ?brs|polybrss|poly brass|analog brass|slap brass|rich brass|flutish brass|velo brass|brass attack|horn blast|mks ?80 brass|(?:d ?50|juno(?: ?(?:60|106))?|jupiter(?: ?8)?|jp ?(?:6|8|8000)|jx|jd ?(?:80|800)|jv ?1080|xv ?5080|m ?1|triton|trinity|kronos|krome|kross|korg) (?:soft )?brass)\b/ },
  { name: 'Synth Strings', pattern: /\b(synth strings?|syn strings?|synthstrings|syn ?str(?:ings?)?|(?:d ?50|juno(?: ?(?:6|60|106))?|jupiter(?: ?8)?|jp ?(?:6|8|8000)|jx|jd ?(?:80|800)) (?:slow )?str(?:ings?)?)\b/ },
  { name: 'Saw', pattern: /\b(saw|sawtooth)\b/ },
  { name: 'Square', pattern: /\b(square|square wave)\b/ },
  { name: 'Pulse', pattern: /\b(pulse|pulse wave)\b/ },
  { name: 'Pad', pattern: /\b(pads?|d ?50 heaven|d ?50 stack pad|(?:sft|brt|choir|syn|str|bell|vox|jup ?8|jp ?8) ?pd)\b/ },
  { name: 'Synth', pattern: /\b(synth|synthesizer|sintetizador|fast synth|slow synth|motion synth|poly ?synth|pulsating)\b/ },
  { name: 'Lead', pattern: /\b(leads?|(?:sft|syn|synth|saw|square|sqr|mono|jp ?6|jp ?8|juno) ?ld)\b/ },
  { name: 'Pluck', pattern: /\b(pluck|plucked)\b/ },
  { name: 'Arp', pattern: /\b(arp|arpeggio|arpejo)\b/ },
  { name: 'Teclado', pattern: /\b(teclado|keyboard|keys?|poly ?keys?|polykey)\b/ },
  { name: 'Cordas', pattern: /\b(cordas|strings?)\b/ },
  { name: 'Hit', pattern: /\b(orch ?hits?|orchhits?|orchestra ?hits?|orchestral ?hits?|orquestra ?hits?|orquestral ?hits?|orq ?hits?|orqhits?|brass ?hits?|double ?hits?|euro ?hits?|impact|stabs?|hits?)\b/ },
  { name: 'Percussão', pattern: /\b(percussao|percussion|perc)\b/ },
  { name: 'Metais', pattern: /(?:\b(metais|naipe(?: de metais)?|nipe(?: de metais)?|brass(?: sections?| ensembles?| falls?)?|brss ?sec(?:t(?:ion)?)?s?|brss ?falls?|sopros?|horn ?(?:sections?|orchestra|orch|swell)|hornorch|(?:noble|massed|afro) horns?|sax sections?|trumpet (?:and|&) trombone sections?|tp ?(?:and|&) ?tb ?sec(?:t(?:ion)?)?s?)\b|^horns?(?=\s+(?:l|r|\d+)\b|$))/ },
  { name: 'Trompete Piccolo', pattern: /\b(trompete piccolo|piccolo trumpet)\b/ },
  { name: 'Trompete Baixo', pattern: /\b(trompete baixo|bass trumpet)\b/ },
  { name: 'Trompete', pattern: /\b(trompetes?|trumpets?|muted trumpet|mute trp|warm trp|trp|tpt)\b/ },
  { name: 'Corneta', pattern: /\b(cornetas?|cornets?)\b/ },
  { name: 'Flugelhorn', pattern: /\b(flugelhorns?|flugels?|fliscornes?|flicornes?)\b/ },
  { name: 'Trombone Baixo', pattern: /\b(trombone baixo|bass trombone)\b/ },
  { name: 'Trombone Alto', pattern: /\b(trombone alto|alto trombone)\b/ },
  { name: 'Trombone Tenor', pattern: /\b(trombone tenor|tenor trombone)\b/ },
  { name: 'Trombone', pattern: /\b(trombones?|valve trombone|tbn)\b/ },
  { name: 'Sax Soprano', pattern: /\b(sax(?:ofone)? soprano|soprano sax(?:ophone)?|sprno ?sax)\b/ },
  { name: 'Sax Alto', pattern: /\b(sax(?:ofone)? alto|alto sax(?:ophone)?)\b/ },
  { name: 'Sax Tenor', pattern: /\b(sax(?:ofone)? tenor|tenor sax(?:ophone)?)\b/ },
  { name: 'Sax Barítono', pattern: /\b(sax(?:ofone)? baritono|baritone sax(?:ophone)?|bari ?sax)\b/ },
  { name: 'Sax', pattern: /\b(saxes|sax|saxofones?|saxophones?)\b/ },
  { name: 'Tuba', pattern: /\b(tuba|tubas)\b/ },
  { name: 'Sousafone', pattern: /\b(sousafones?|sousaphones?)\b/ },
  { name: 'Bombardino', pattern: /\b(bombardinos?|eufonios?|euphoniums?)\b/ },
  { name: 'Barítono de Metal', pattern: /\b(baritono de metal|baritone horns?|marching baritones?)\b/ },
  { name: 'Trompa Alto', pattern: /\b(trompa (?:alto|tenor)|alto horns?|tenor horns?)\b/ },
  { name: 'Mellophone', pattern: /\b(mellophones?|melofones?)\b/ },
  { name: 'Trompa', pattern: /\b(trompas?|french horns?|fr ?horns?|corno frances)\b/ },
  { name: 'Clarim', pattern: /\b(clarins?|bugles?)\b/ },
  { name: 'Shofar', pattern: /\b(shofars?|shofarot|shofroth|schofars?)\b/ },
  { name: 'Piccolo', pattern: /\b(piccolo)\b/ },
  { name: 'Flauta Pan', pattern: /\b(flauta pan|pan flute)\b/ },
  { name: 'Flauta', pattern: /\b(flauta|flute)\b/ },
  { name: 'Clarinete', pattern: /\b(clarinete|clarinet)\b/ },
  { name: 'Oboé', pattern: /\b(oboe)\b/ },
  { name: 'Fagote', pattern: /\b(fagote|bassoon)\b/ },
  { name: 'Recorder', pattern: /\b(recorder)\b/ },
  { name: 'Ocarina', pattern: /\b(ocarina)\b/ },
  { name: 'Harmônica', pattern: /\b(harmonica|gaita de boca)\b/ },
  { name: 'Violino', pattern: /\b(violino|violin|fiddle)\b/ },
  { name: 'Viola', pattern: /\b(viola)\b/ },
  { name: 'Cello', pattern: /\b(cello|violoncelo)\b/ },
  { name: 'Harpa', pattern: /\b(harpa|harp)\b/ },
  { name: 'Sitar', pattern: /\b(sitar)\b/ },
  { name: 'Koto', pattern: /\b(koto|shamisen)\b/ },
  { name: 'Orquestra', pattern: /\b(orquestra|orchestra|ensemble)\b/ },
  { name: 'Coro', pattern: /\b(coro|choir)\b/ },
  { name: 'Sequencer', pattern: /\b(sequencer|sequence|sequencia|sequenciador|seq)\b/ },
  { name: 'FX', pattern: /\b(fx|sfx|efeito|efeitos)\b/ },
  { name: 'Loop', pattern: /\b(loop)\b/ },
  { name: 'Playback', pattern: /\b(playback|pb)\b/ },
  { name: 'Solo', pattern: /\bsolo\b/ },
  { name: 'Vinheta', pattern: /\b(vinheta|vinhetas)\b/ },
  { name: 'Universe', pattern: /\b(universe)\b/ },
  { name: 'Fantasia', pattern: /\b(fantasia(?: jv)?|fantasy)\b/ },
  { name: 'Staccato Heaven', pattern: /\b((?:staccato|stac) heaven)\b/ },
  { name: 'Digital Native Dance', pattern: /\b(digital native dance|native dance)\b/ },
  { name: 'Pizzagogo', pattern: /\b(pizzagogo)\b/ },
  { name: 'Glass Voices', pattern: /\b(glass voices?|glass vox)\b/ },
  { name: 'Soundtrack', pattern: /\b(sound ?track)\b/ },
  { name: 'M1', pattern: /\b(?:korg )?m ?1\b/ },
  { name: 'Triton', pattern: /\b(?:korg )?triton(?: studio| le| extreme| rack)?\b/ },
  { name: 'Trinity', pattern: /\b(?:korg )?trinity\b/ },
  { name: 'Kronos', pattern: /\b(?:korg )?kronos\b/ },
  { name: 'Nautilus', pattern: /\b(?:korg )?nautilus\b/ },
  { name: 'Krome', pattern: /\b(?:korg )?krome\b/ },
  { name: 'Kross', pattern: /\b(?:korg )?kross(?: ?2)?\b/ },
  { name: 'Wavestation', pattern: /\b(?:korg )?wavestation\b/ },
  { name: 'Wavestate', pattern: /\b(?:korg )?wavestate\b/ },
  { name: 'Polysix', pattern: /\b(?:korg )?polysix\b/ },
  { name: 'MS-20', pattern: /\b(?:korg )?ms ?20\b/ },
  { name: 'Opsix', pattern: /\b(?:korg )?opsix\b/ },
  { name: 'Modwave', pattern: /\b(?:korg )?modwave\b/ },
  { name: 'Minilogue', pattern: /\b(?:korg )?minilogue(?: xd)?\b/ },
  { name: 'KingKORG', pattern: /\bking ?korg\b/ },
  { name: 'Korg PA', pattern: /\b(?:korg )?pa ?(?:5 x|4 x|1000|700|600)\b/ },
  { name: 'Korg', pattern: /\bkorg\b/ },
  { name: 'D-50', pattern: /\b(?:roland )?d ?50\b/ },
  { name: 'JD-800', pattern: /\b(?:roland )?jd ?(?:80|800|990|08)\b/ },
  { name: 'JV-1080', pattern: /\b(?:roland )?jv ?(?:1080|2080)\b/ },
  { name: 'XV-5080', pattern: /\b(?:roland )?xv ?(?:5050|5080)\b/ },
  { name: 'XP', pattern: /\b(?:roland )?xp ?(?:30|50|60|80)\b/ },
  { name: 'Juno', pattern: /\b(?:roland )?juno(?: ?(?:6|60|106|x|x m|ds))?\b/ },
  { name: 'Jupiter', pattern: /\b(?:roland )?(?:jupiter(?: ?(?:6|8|x|x m))?|jp ?(?:6|8|8000))\b/ },
  { name: 'Fantom', pattern: /\b(?:roland )?fantom(?: ?(?:06|07|08|6|7|8|g|x))?\b/ },
  { name: 'Integra-7', pattern: /\b(?:roland )?integra ?7\b/ },
  { name: 'RD', pattern: /\b(?:roland )?rd ?(?:1000|2000|700|800|88)\b/ },
  { name: 'SH-101', pattern: /\b(?:roland )?sh ?(?:101|2|4 d)\b/ },
  { name: 'JX', pattern: /\b(?:roland )?jx ?(?:3 p|8 p|08)\b/ },
  { name: 'System-8', pattern: /\b(?:roland )?system ?8\b/ },
  { name: 'Roland', pattern: /\broland\b/ }
];

const CREATE_PROJECT_TRACK_GROUPS = [
  { key: 'interno', name: 'Interno', trackNames: new Set(['Regência', 'Click', 'Guia']) },
  { key: 'guitarras', name: 'Guitarras', trackNames: new Set(['Guitarra']) },
  { key: 'violoes', name: 'Violões', trackNames: new Set(['Violão', 'Violão Nylon', 'Ukulele', 'Cavaquinho', 'Banjo', 'Bandolim']) },
  { key: 'sanfonas', name: 'Sanfonas', trackNames: new Set(['Sanfona']) },
  {
    key: 'teclados',
    name: 'Teclados',
    trackNames: new Set(['Teclado', 'Piano', 'Rhodes', 'Wurlitzer', 'Electric Piano', 'CP80', 'DX', 'Honky Tonk', 'Clavi', 'Hammond', 'Órgão', 'Cravo', 'Celesta', 'Glockenspiel', 'Music Box', 'Bells', 'Mallet', 'Synth Brass', 'Synth Strings', 'Saw', 'Square', 'Pulse', 'Pad', 'Vox Synth', 'Synth', 'Lead', 'Pluck', 'Arp', 'Cordas', 'Hit', 'Universe', 'Fantasia', 'Staccato Heaven', 'Digital Native Dance', 'Pizzagogo', 'Glass Voices', 'Soundtrack', 'M1', 'Triton', 'Trinity', 'Kronos', 'Nautilus', 'Krome', 'Kross', 'Wavestation', 'Wavestate', 'Polysix', 'MS-20', 'Opsix', 'Modwave', 'Minilogue', 'KingKORG', 'Korg PA', 'Korg', 'D-50', 'JD-800', 'JV-1080', 'XV-5080', 'XP', 'Juno', 'Jupiter', 'Fantom', 'Integra-7', 'RD', 'SH-101', 'JX', 'System-8', 'Roland'])
  },
  {
    key: 'metais',
    name: 'Metais',
    trackNames: new Set(['Metais', 'Trompete Piccolo', 'Trompete Baixo', 'Trompete', 'Corneta', 'Flugelhorn', 'Trombone Baixo', 'Trombone Alto', 'Trombone Tenor', 'Trombone', 'Sax Soprano', 'Sax Alto', 'Sax Tenor', 'Sax Barítono', 'Sax', 'Tuba', 'Sousafone', 'Bombardino', 'Barítono de Metal', 'Trompa Alto', 'Mellophone', 'Trompa', 'Clarim', 'Shofar'])
  },
  {
    key: 'percussivo',
    name: 'Percussivo',
    trackNames: new Set(['Bumbo', 'Caixa', 'Hi-Hat', 'Tom', 'Over', 'Reverse Cymbal', 'Pratos', 'Ride', 'Crash', 'Conga', 'Bongo', 'Timbal', 'Surdo', 'Repique de Mão', 'Repique', 'Meia Lua', 'Pandeiro', 'Pandeirola', 'Bacurinha', 'Tamborim', 'Shaker', 'Ganzá', 'Agogô', 'Cowbell', 'Clave', 'Triângulo', 'Cajón', 'Djembe', 'Darbuka', 'Cabasa', 'Maracas', 'Chocalho', 'Cuíca', 'Berimbau', 'Caxixi', 'Reco-Reco', 'Afoxé', 'Alfaia', 'Zabumba', 'Atabaque', 'Tantã', 'Rebolo', 'Sopapo', 'Tarol', 'Xequerê', 'Rocar', 'Palmas', 'Snap', 'Rimshot', 'Tímpano', 'Tabla', 'Taiko', 'Tambora', 'Bodhrán', 'Frame Drum', 'Talking Drum', 'Gong', 'Jamblock', 'Bloco', 'Woodblock', 'Bar Chimes', 'Bell Tree', 'Waterfall', 'Vibraslap', 'Castanholas', 'Apito', 'Udu', 'Bateria', 'Percussão'])
  },
  { key: 'back-vocais', name: 'Back Vocais', trackNames: new Set(['Backing Vocal', 'Vocal', 'Vox', 'Coro']) },
  { key: 'outros', name: 'Outros', trackNames: null }
];

const CREATE_PROJECT_GROUP_COLOR_PALETTE = [
  { red: 255, green: 105, blue: 105 },
  { red: 255, green: 184, blue: 76 },
  { red: 104, green: 211, blue: 145 },
  { red: 74, green: 190, blue: 230 },
  { red: 117, green: 137, blue: 255 },
  { red: 202, green: 112, blue: 255 },
  { red: 240, green: 105, blue: 180 },
  { red: 205, green: 218, blue: 70 },
  { red: 90, green: 220, blue: 205 }
];

const TRACK_PRIORITY = new Map(CREATE_PROJECT_TRACK_RULES.map((rule, index) => [rule.name, index]));
const KEYBOARD_MODEL_REFERENCE_PATTERN = /\b(?:korg|roland|m ?1|triton(?: studio| le| extreme| rack)?|trinity|kronos|nautilus|krome|kross(?: ?2)?|wavestation|wavestate|polysix|ms ?20|opsix|modwave|minilogue(?: xd)?|king ?korg|pa ?(?:5 x|4 x|1000|700|600)|d ?50|jd ?(?:80|800|990|08)|jv ?(?:1080|2080)|xv ?(?:5050|5080)|xp ?(?:30|50|60|80)|juno(?: ?(?:6|60|106|x|xm|x m|ds))?|jupiter(?: ?(?:6|8|x|xm|x m))?|jp ?(?:6|8|8000)|fantom(?: ?(?:06|07|08|6|7|8|g|x))?|integra ?7|rd ?(?:1000|2000|700|800|88)|sh ?(?:101|2|4 d)|jx ?(?:3 p|8 p|08)|system ?8)\b/g;

function normalizeWords(value) {
  return String(value || '')
    .replace(/([a-zà-ÿ])([A-Z])/g, '$1 $2')
    .replace(/([A-Za-zÀ-ÿ])(\d)/g, '$1 $2')
    .replace(/(\d)([A-Za-zÀ-ÿ])/g, '$1 $2')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[_.,()[\]{}]+/g, ' ')
    .replace(/\s*[-–—]+\s*/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function normalizeTrackKey(value) {
  return normalizeWords(value).replace(/\s+/g, ' ');
}

// Marcas e plataformas que costumam vir junto do nome da pasta baixada. A
// comparação é feita com o texto normalizado e com a expressão inteira para
// não remover palavras genéricas de títulos reais (por exemplo: "Loop de
// Amor", "Primeiro Amor", "Worship You" ou "Studio 54").
const SONG_FOLDER_SOURCE_LABEL_PATTERN_SOURCE = [
  'vs\\s+(?:professional|profissional|premium|pro|sertanejo|gospel)',
  'clube\\s+(?:do|de)\\s+vs',
  'playback\\s+(?:professional|studio)',
  'pacote\\s+vs',
  'multi\\s*tracks\\s+for\\s+worship',
  'multi\\s*tracks(?:\\s+com(?:\\s+br)?)?',
  'loop\\s*community(?:\\s+com)?',
  'prime\\s+by\\s+loop\\s*community',
  'praise\\s*charts(?:\\s+com)?',
  'worship\\s*backing\\s*(?:tracks|band)(?:\\s+com)?',
  'custom\\s*backing\\s*tracks(?:\\s+(?:com|net))?',
  'karaoke\\s*version(?:\\s+com)?',
  'song\\s*galaxy(?:\\s+com)?',
  'jam\\s*zone(?:\\s+com)?',
  'jam\\s*kazam(?:\\s+com)?',
  'hit\\s*trax',
  'supreme\\s+(?:tracks|midi|network)',
  'midi\\s*art(?:\\s+store)?',
  'extreme\\s+backing\\s*tracks',
  'jetset\\s+sound',
  'shred\\s*trax'
].join('|');

const SONG_FOLDER_LABEL_PATTERN = new RegExp(
  `^(?:www\\s+)?(?:${SONG_FOLDER_SOURCE_LABEL_PATTERN_SOURCE})(?:\\s+(?:com(?:\\s+(?:br|au))?|co\\s+uk|net|org|store|ca))?(?:\\s+\\d{2,4})?$`,
  'i'
);

// Shared with Hook Rename suggestions. Track vocabulary and download-source
// labels are separate taxonomies: removing a provider tag must stay possible.
const SONG_FOLDER_EMBEDDED_LABEL_PATTERN = new RegExp(
  `\\b(?:${SONG_FOLDER_SOURCE_LABEL_PATTERN_SOURCE})\\b`, 'gi'
);

function isCreateProjectSourceLabel(value) {
  return SONG_FOLDER_LABEL_PATTERN.test(normalizeWords(value));
}

function isCreateProjectTrackLabel(value) {
  const normalized = normalizeWords(value);
  if (!normalized || isCreateProjectSourceLabel(normalized)) return false;
  if (CREATE_PROJECT_TRACK_RULES.some(rule => normalizeWords(rule.name) === normalized) || CREATE_PROJECT_TRACK_GROUPS.some(group => normalizeWords(group.name) === normalized)) return true;
  return CREATE_PROJECT_TRACK_RULES.some((rule) => {
    const match = normalized.match(rule.pattern);
    return match && match[0] === normalized;
  });
}

function containsCreateProjectTrackName(value) {
  const normalized = normalizeWords(value)
    .replace(SONG_FOLDER_EMBEDDED_LABEL_PATTERN, ' ').replace(/\s+/g, ' ').trim();
  if (!normalized) return false;
  // Check both the phrase (Electric Piano, Hi-Hat...) and its words so that
  // anchored aliases such as Vocal/Vox also stay out of mixed suggestions.
  const candidates = [normalized, ...normalized.split(' ')];
  return candidates.some((candidate) =>
    CREATE_PROJECT_TRACK_RULES.some((rule) => rule.pattern.test(candidate)));
}

// Versão para reconhecer as mesmas marcas no começo/fim do texto original,
// preservando pontos e hífens de domínios como MultiTracks.com.br.
const SONG_FOLDER_RAW_LABEL_PATTERN_SOURCE = [
  'vs\\s+(?:professional|profissional|premium|pro|sertanejo|gospel)',
  'clube\\s+(?:do|de)\\s+vs',
  'playback\\s+(?:professional|studio)',
  'pacote\\s+vs',
  'multi\\s*tracks\\s+for\\s+worship',
  'multi\\s*tracks(?:\\s*\\.\\s*com(?:\\s*\\.\\s*br)?)?',
  'loop\\s*community(?:\\s*\\.\\s*com)?',
  'prime\\s+by\\s+loop\\s*community',
  'praise\\s*charts(?:\\s*\\.\\s*com)?',
  'worship\\s*backing\\s*(?:tracks|band)(?:\\s*\\.\\s*com)?',
  'custom\\s*backing\\s*tracks(?:\\s*\\.\\s*(?:com|net))?',
  'karaoke\\s*[- ]?\\s*version(?:\\s*\\.\\s*com)?',
  'song\\s*galaxy(?:\\s*\\.\\s*com)?',
  'jam\\s*zone(?:\\s*\\.\\s*com)?',
  'jam\\s*kazam(?:\\s*\\.\\s*com)?',
  'hit\\s*trax',
  'supreme\\s*[- ]?\\s*(?:tracks|midi|network)',
  'midi\\s*art(?:\\s*\\.\\s*store)?',
  'extreme\\s+backing\\s*tracks',
  'jetset\\s+sound',
  'shred\\s*trax'
].join('|');

function inferSongNameFromFolder(folderPathOrName) {
  const rawName = path.basename(String(folderPathOrName || '')).trim();
  const removedLabels = [];
  let working = rawName
    .replace(/[\[(]([^\])]+)[\])]/g, (full, content) => {
      if (!SONG_FOLDER_LABEL_PATTERN.test(normalizeWords(content))) return full;
      removedLabels.push(content.trim());
      return ' ';
    })
    .replace(/^\s*\d{1,3}\s*[.)_-]+\s*/, '')
    .trim();

  const pieces = working.split(/\s+(?:-|–|—|\||•)\s+|\s*_{2,}\s*/).filter(Boolean);
  const titlePieces = pieces.filter((piece) => {
    if (!SONG_FOLDER_LABEL_PATTERN.test(normalizeWords(piece))) return true;
    removedLabels.push(piece.trim());
    return false;
  });
  if (titlePieces.length) working = titlePieces.join(' - ');

  const suffixPattern = new RegExp(
    `(?:\\s*[-–—|_()]\\s*)?((?:www\\s*\\.\\s*)?(?:${SONG_FOLDER_RAW_LABEL_PATTERN_SOURCE})(?:\\s*\\.\\s*(?:com(?:\\s*\\.\\s*(?:br|au))?|co\\s*\\.\\s*uk|net|org|store|ca))?)(?:\\s+\\d{2,4})?\\s*$`,
    'i'
  );
  const prefixPattern = new RegExp(
    `^\\s*((?:www\\s*\\.\\s*)?(?:${SONG_FOLDER_RAW_LABEL_PATTERN_SOURCE})(?:\\s*\\.\\s*(?:com(?:\\s*\\.\\s*(?:br|au))?|co\\s*\\.\\s*uk|net|org|store|ca))?)(?:\\s+\\d{2,4})?(?:\\s*[-–—|_:]\\s*)?`,
    'i'
  );
  let match = working.match(suffixPattern);
  if (match) {
    removedLabels.push(match[1]);
    working = working.slice(0, match.index).trim();
  }
  match = working.match(prefixPattern);
  if (match) {
    removedLabels.push(match[1]);
    working = working.slice(match[0].length).trim();
  }

  working = working.replace(/\s{2,}/g, ' ').replace(/^[-–—|_: ]+|[-–—|_: ]+$/g, '').trim();
  const name = working || rawName;
  return {
    name,
    rawName,
    changed: removedLabels.length > 0 || normalizeWords(name) !== normalizeWords(rawName),
    removedLabels: [...new Set(removedLabels.filter(Boolean))]
  };
}

function isSupportedAudioFile(filePath) {
  return SUPPORTED_AUDIO_EXTENSIONS.has(path.extname(String(filePath || '')).toLowerCase());
}

function stripSongName(fileStem, folderName) {
  const stem = normalizeWords(fileStem).replace(/^\s*\d{1,3}(?:\s+|(?=[a-z]))/, '').trim();
  const song = normalizeWords(folderName);
  if (!song) return stem;
  if (stem === song) return '';
  if (stem.endsWith(` ${song}`)) return stem.slice(0, -(song.length + 1)).trim();
  if (stem.startsWith(`${song} `)) return stem.slice(song.length + 1).trim();
  return stem;
}

function inferUnknownTrackCandidate(fileStem, folderName = '') {
  const normalizedName = stripSongName(fileStem, folderName)
    .replace(/^\s*\d{1,3}\s+/, '')
    .replace(/\s+/g, ' ')
    .trim();
  if (!normalizedName) return null;

  const acronyms = new Map([
    ['dj', 'DJ'],
    ['fx', 'FX'],
    ['midi', 'MIDI'],
    ['sfx', 'SFX']
  ]);
  const name = normalizedName
    .split(' ')
    .map((word) => acronyms.get(word) || `${word.charAt(0).toUpperCase()}${word.slice(1)}`)
    .join(' ');
  return { name, key: `custom:${normalizeTrackKey(normalizedName)}` };
}

function findVariant(normalizedName, rule) {
  const withoutBase = normalizedName
    .replace(rule.pattern, ' ')
    .replace(KEYBOARD_MODEL_REFERENCE_PATTERN, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  const variants = [];
  const has = (pattern) => pattern.test(withoutBase);

  if (has(/\b(base|rhythm|ritmo)\b/)) variants.push('Base');
  if (has(/\b(solo)\b/)) variants.push('Solo');
  if (has(/\b(lead)\b/)) variants.push('Lead');
  if (has(/\b(clean|limpo)\b/)) variants.push('Clean');
  if (has(/\b(drive|dist|distorcao|distortion)\b/)) variants.push('Drive');
  if (has(/\b(midi)\b/)) variants.push('MIDI');

  const left = has(/\b(l|left|esq|esquerda)\b/);
  const right = has(/\b(r|right|dir|direita)\b/);
  if (left && !right) variants.push('L');
  if (right && !left) variants.push('R');

  const number = withoutBase.match(/(?:^|\s)([1-9]\d?)(?:\s|$)/);
  if (number) variants.push(number[1]);
  return [...new Set(variants)].join(' ');
}

function classifyCreateProjectTrack(filePath, folderName = '') {
  const fileName = path.basename(String(filePath || ''));
  const fileStem = path.basename(fileName, path.extname(fileName));
  const normalizedName = stripSongName(fileStem, folderName);
  const rule = CREATE_PROJECT_TRACK_RULES.find((item) => item.pattern.test(normalizedName));

  if (!rule) {
    const candidate = inferUnknownTrackCandidate(fileStem, folderName);
    return {
      name: 'Out',
      key: 'out',
      recognized: false,
      sourceName: fileStem,
      candidateName: candidate?.name || '',
      candidateKey: candidate?.key || ''
    };
  }

  // As pistas internas representam uma função única, independentemente de
  // complementos como "Base", "Voz" ou do nome usado pelo fornecedor.
  const internalTrack = rule.name === 'Click' || rule.name === 'Regência' || rule.name === 'Guia';
  const variant = internalTrack ? '' : findVariant(normalizedName, rule);
  const name = variant ? `${rule.name} ${variant}` : rule.name;
  return { name, key: normalizeTrackKey(name), recognized: true, sourceName: fileStem };
}

function inferSongNameFromAudioFiles(audioFiles, folderInference) {
  const candidates = new Map();
  for (const filePath of audioFiles) {
    const stem = path.basename(filePath, path.extname(filePath)).replace(/^\s*\d{1,3}\s*[.)_-]+\s*/, '').trim();
    const parts = stem.split(/\s*[_|]\s*|\s+[-–—]\s+/).map((part) => part.trim()).filter(Boolean);
    while (parts.length && /^\d{1,3}$/.test(parts[0])) parts.shift();
    if (parts.length < 2) continue;
    let candidate = '';
    for (let index = 0; index < parts.length - 1; index += 1) {
      const possibleTrack = parts.slice(0, index + 1).join(' ');
      if (!classifyCreateProjectTrack(possibleTrack).recognized) continue;
      candidate = parts.slice(index + 1).join(' - ').trim();
      break;
    }
    if (!candidate || candidate.length < 2) continue;
    const cleaned = inferSongNameFromFolder(candidate);
    const key = normalizeWords(cleaned.name);
    if (!key || SONG_FOLDER_LABEL_PATTERN.test(key)) continue;
    if (!candidates.has(key)) candidates.set(key, { ...cleaned, count: 0 });
    candidates.get(key).count += 1;
  }
  const best = [...candidates.values()].sort((a, b) => b.count - a.count || a.name.length - b.name.length)[0];
  const minimumAgreement = Math.min(2, audioFiles.length);
  if (!best || best.count < minimumAgreement) return { ...folderInference, source: folderInference.changed ? 'folder-cleaned' : 'folder' };

  const folderKey = normalizeWords(folderInference.name);
  const fileKey = normalizeWords(best.name);
  if (folderKey === fileKey || folderKey.includes(fileKey)) {
    return {
      ...best,
      rawName: folderInference.rawName,
      changed: fileKey !== normalizeWords(folderInference.rawName),
      removedLabels: [...new Set([...(folderInference.removedLabels || []), ...(best.removedLabels || [])])],
      source: fileKey === folderKey ? (folderInference.changed ? 'folder-cleaned' : 'folder') : 'audio-files'
    };
  }
  // Um título repetido em vários stems é um sinal forte, mas só substitui a
  // pasta automaticamente quando a pasta já contém uma etiqueta conhecida.
  if (folderInference.changed && best.count >= Math.ceil(audioFiles.length / 2)) {
    return {
      ...best,
      rawName: folderInference.rawName,
      changed: true,
      removedLabels: [...new Set([...(folderInference.removedLabels || []), ...(best.removedLabels || [])])],
      source: 'audio-files'
    };
  }
  return { ...folderInference, source: folderInference.changed ? 'folder-cleaned' : 'folder' };
}

function compareTracks(a, b) {
  const baseA = CREATE_PROJECT_TRACK_RULES.find((rule) => a.name === rule.name || a.name.startsWith(`${rule.name} `));
  const baseB = CREATE_PROJECT_TRACK_RULES.find((rule) => b.name === rule.name || b.name.startsWith(`${rule.name} `));
  const priorityA = a.name === 'Out' ? 10000 : (TRACK_PRIORITY.get(baseA?.name) ?? 9999);
  const priorityB = b.name === 'Out' ? 10000 : (TRACK_PRIORITY.get(baseB?.name) ?? 9999);
  return priorityA - priorityB || a.name.localeCompare(b.name, 'pt-BR', { numeric: true });
}

function getCreateProjectTrackBaseName(trackName) {
  const name = String(trackName || '');
  return CREATE_PROJECT_TRACK_RULES
    .filter((rule) => name === rule.name || name.startsWith(`${rule.name} `))
    .sort((left, right) => right.name.length - left.name.length)[0]?.name || 'Out';
}

function resolveCreateProjectTrackGroup(trackName) {
  const baseName = getCreateProjectTrackBaseName(trackName);
  return CREATE_PROJECT_TRACK_GROUPS.find((group) => group.trackNames?.has(baseName)) ||
    CREATE_PROJECT_TRACK_GROUPS[CREATE_PROJECT_TRACK_GROUPS.length - 1];
}

function reaperCustomColor({ red, green, blue }) {
  return 0x1000000 | red | (green << 8) | (blue << 16);
}

function cssColor({ red, green, blue }) {
  return `#${[red, green, blue].map((value) => value.toString(16).padStart(2, '0')).join('')}`;
}

function createProjectTrackGroups(tracks = []) {
  const palette = CREATE_PROJECT_GROUP_COLOR_PALETTE.map((color) => ({ ...color }));
  for (let index = palette.length - 1; index > 0; index -= 1) {
    const other = crypto.randomInt(index + 1);
    [palette[index], palette[other]] = [palette[other], palette[index]];
  }
  return CREATE_PROJECT_TRACK_GROUPS
    .map((definition) => {
      const groupTracks = tracks.filter((track) => resolveCreateProjectTrackGroup(track.name).key === definition.key);
      if (!groupTracks.length) return null;
      const color = palette.shift() || CREATE_PROJECT_GROUP_COLOR_PALETTE[0];
      return {
        key: definition.key,
        name: definition.name,
        color: reaperCustomColor(color),
        colorHex: cssColor(color),
        tracks: groupTracks
      };
    })
    .filter(Boolean);
}

function splitRemovalTexts(value) {
  return [...new Set(String(value || '').split(',').map((text) => text.trim()).filter(Boolean))];
}

function foldRemovalValue(value) {
  let text = '';
  const map = [];
  let offset = 0;
  for (const character of String(value || '')) {
    const start = offset;
    offset += character.length;
    const folded = character.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
    if (!folded) {
      if (map.length) map[map.length - 1].end = offset;
      continue;
    }
    for (const foldedCharacter of folded) {
      const separator = /[\s._\-–—]/u.test(foldedCharacter);
      if (separator && text.endsWith(' ')) {
        map[map.length - 1].end = offset;
        continue;
      }
      text += separator ? ' ' : foldedCharacter;
      map.push({ start, end: offset });
    }
  }
  return { text, map };
}

function removalName(name, text, directory) {
  // Literal text, without sensitivity to case, accents or common separators.
  // File extensions stay intact.
  const extension = directory ? '' : path.extname(name);
  const stem = extension ? name.slice(0, -extension.length) : name;
  const texts = Array.isArray(text) ? text : splitRemovalTexts(text);
  const foldedStem = foldRemovalValue(stem);
  const foldedTexts = [...new Set(texts.map((item) => foldRemovalValue(item).text.trim()).filter(Boolean))]
    .sort((a, b) => b.length - a.length);
  if (!foldedTexts.length) return null;

  // Uma única leitura do nome original, priorizando os termos mais longos.
  // Assim, remover um termo não cria por acidente uma nova correspondência.
  const ranges = [];
  for (let index = 0; index < foldedStem.text.length;) {
    const match = foldedTexts.find((item) => foldedStem.text.startsWith(item, index));
    if (!match) {
      index += 1;
      continue;
    }
    const first = foldedStem.map[index];
    const last = foldedStem.map[index + match.length - 1];
    if (first && last) ranges.push({ start: first.start, end: last.end });
    index += match.length;
  }
  if (!ranges.length) return null;

  let cursor = 0;
  let nextStem = '';
  for (const range of ranges) {
    nextStem += stem.slice(cursor, range.start);
    cursor = range.end;
  }
  nextStem = `${nextStem}${stem.slice(cursor)}`
    .replace(/^[\s._\-–—]+|[\s._\-–—]+$/gu, '')
    .replace(/\s{2,}/g, ' ')
    .trim();
  const nextName = nextStem + extension;
  if (!nextStem || nextStem === '.' || nextStem === '..' ||
      /[<>:"/\\|?*\u0000-\u001f]/.test(nextName) || /[. ]$/.test(nextName) ||
      /^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(nextName)) {
    return { invalid: true, name: nextName };
  }
  return nextName === name ? null : { name: nextName };
}

function suggestRepeatedNames(names, { limit = 5 } = {}) {
  const counts = new Map();
  const sourceLabels = new Map();
  const trackLabels = new Map();
  const cached = (cache, detector, value) => {
    if (!cache.has(value)) cache.set(value, detector(value));
    return cache.get(value);
  };
  for (const name of names) {
    const tokens = [...name.matchAll(/[^\s_\-()[\]{}.,]+/gu)];
    const supplierTokens = new Set();
    const trackTokens = new Set();
    const windows = [];
    for (let start = 0; start < tokens.length; start += 1) {
      for (let size = 1; size <= 6 && start + size <= tokens.length; size += 1) {
        const last = tokens[start + size - 1];
        const text = name.slice(tokens[start].index, last.index + last[0].length);
        windows.push({ start, size, text });
        if (cached(sourceLabels, isCreateProjectSourceLabel, text)) {
          for (let i = start; i < start + size; i += 1) supplierTokens.add(i);
        }
      }
    }
    for (const { start, size, text } of windows) {
      if (Array.from({ length: size }, (_, i) => start + i).some((i) => supplierTokens.has(i))) continue;
      if (cached(trackLabels, isCreateProjectTrackLabel, text)) {
        for (let i = start; i < start + size; i += 1) trackTokens.add(i);
      }
    }
    const perItem = new Set();
    for (const { start, size, text } of windows) {
      if (Array.from({ length: size }, (_, i) => start + i).some((i) => trackTokens.has(i))) continue;
      if (text.length < 2 || text.length > 120 || !/\p{L}/u.test(text)) continue;
      perItem.add(text);
    }
    for (const text of perItem) counts.set(text, (counts.get(text) || 0) + 1);
  }
  const candidates = [...counts]
    .filter(([text, count]) => count > 1 && !containsCreateProjectTrackName(text))
    .map(([text, count]) => [text, count, cached(sourceLabels, isCreateProjectSourceLabel, text)])
    // Prefer the complete provider tag over generic pieces such as "VS".
    // Never use the song-name cleanup here: it would erase the very brands
    // the user is trying to remove from their folders and files.
    .sort((a, b) => Number(b[2]) - Number(a[2]) || b[1] - a[1] ||
      b[0].length - a[0].length || a[0].localeCompare(b[0]));
  const suggestions = [];
  for (const [text, count] of candidates) {
    // Prefer the complete repeated phrase over five variations of its words.
    if (suggestions.some((item) => item.text.includes(text) || text.includes(item.text))) continue;
    suggestions.push({ text, count });
    if (suggestions.length >= limit) break;
  }
  return suggestions;
}

function calculatePeakNormalizationGain(peakDb, targetDb = CREATE_PROJECT_INTERNAL_PEAK_DB) {
  const sourcePeak = Number(peakDb);
  const targetPeak = Number(targetDb);
  if (!Number.isFinite(sourcePeak) || !Number.isFinite(targetPeak)) return 1;
  return 10 ** ((targetPeak - sourcePeak) / 20);
}

function auditCreateProjectFolders({ folderPaths = [], durationResolver, peakResolver, onProgress } = {}) {
  if (typeof durationResolver !== 'function') throw new Error('Leitor de duração de áudio indisponível.');
  const uniqueFolders = [...new Set(folderPaths.map((item) => path.resolve(String(item || ''))).filter(Boolean))];
  if (!uniqueFolders.length) throw new Error('Escolha pelo menos uma pasta de música.');

  const discoveredSongs = [];
  const emptyFolders = [];
  const skippedFiles = [];
  let discoveredAudioCount = 0;

  for (const folderPath of uniqueFolders) {
    const folderName = path.basename(folderPath);
    const folderSongName = inferSongNameFromFolder(folderName);
    let entries;
    try {
      entries = fs.promises.readdir(folderPath, { withFileTypes: true });
    } catch (error) {
      emptyFolders.push({ folderPath, folderName, reason: `Não foi possível ler a pasta: ${error.message}` });
      continue;
    }
    const files = entries
      .filter((entry) => entry.isFile())
      .map((entry) => path.join(folderPath, entry.name));
    const audioFiles = files.filter(isSupportedAudioFile).sort((a, b) => path.basename(a).localeCompare(path.basename(b), 'pt-BR', { numeric: true }));
    files.filter((item) => !isSupportedAudioFile(item)).forEach((item) => {
      skippedFiles.push({ filePath: item, fileName: path.basename(item), folderName, reason: 'Formato não aceito' });
    });
    if (!audioFiles.length) {
      emptyFolders.push({ folderPath, folderName, reason: 'Nenhum arquivo WAV, AIFF ou MP3 encontrado diretamente nesta pasta.' });
      continue;
    }
    discoveredAudioCount += audioFiles.length;
    const inferredSongName = inferSongNameFromAudioFiles(audioFiles, folderSongName);
    discoveredSongs.push({ folderPath, folderName, inferredSongName, audioFiles });
  }

  let processed = 0;
  // Reserva trinta segundos do grid e mantém trinta segundos entre o fim
  // de uma música e o começo da próxima.
  let timelinePosition = CREATE_PROJECT_REGION_GAP_SECONDS;
  const songs = [];
  const trackMap = new Map();

  for (const discovered of discoveredSongs) {
    const measured = discovered.audioFiles.map((filePath) => {
      const classification = classifyCreateProjectTrack(filePath, discovered.inferredSongName.name);
      try {
        const resolvedDuration = durationResolver(filePath);
        const duration = Number(resolvedDuration);
        if (!Number.isFinite(duration) || duration <= 0) throw new Error('duração inválida');
        const shouldNormalize = classification.name === 'Click' || classification.name === 'Regência';
        const peakDb = shouldNormalize && typeof peakResolver === 'function'
          ? peakResolver(filePath)
          : null;
        const takeVolume = shouldNormalize && peakDb !== null
          ? calculatePeakNormalizationGain(peakDb)
          : 1;
        processed += 1;
        onProgress?.({ phase: 'audit', current: processed, total: discoveredAudioCount, percent: Math.round((processed / discoveredAudioCount) * 100), currentFile: path.basename(filePath) });
        return {
          filePath,
          fileName: path.basename(filePath),
          extension: path.extname(filePath).toLowerCase(),
          duration,
          trackName: classification.name,
          trackKey: classification.key,
          recognized: classification.recognized,
          candidateName: classification.candidateName || '',
          candidateKey: classification.candidateKey || '',
          // O primeiro valor de VOLPAN é o volume do item e permanece 1.
          // A normalização do REAPER é aplicada no ganho do take (3º valor).
          peakDb,
          normalizePeakDb: shouldNormalize && peakDb !== null
            ? CREATE_PROJECT_INTERNAL_PEAK_DB
            : null,
          takeVolume
        };
      } catch (error) {
        processed += 1;
        onProgress?.({ phase: 'audit', current: processed, total: discoveredAudioCount, percent: Math.round((processed / discoveredAudioCount) * 100), currentFile: path.basename(filePath) });
        skippedFiles.push({ filePath, fileName: path.basename(filePath), folderName: discovered.folderName, reason: `Áudio incompatível ou sem duração válida: ${error.message}` });
        return null;
      }
    });
    const files = measured.filter(Boolean);
    if (!files.length) {
      emptyFolders.push({ folderPath: discovered.folderPath, folderName: discovered.folderName, reason: 'Os arquivos encontrados não puderam ser lidos.' });
      continue;
    }

    if (songs.length > 0) timelinePosition += CREATE_PROJECT_REGION_GAP_SECONDS;
    const duration = Math.max(...files.map((item) => item.duration));
    const song = {
      name: discovered.inferredSongName.name,
      sourceFolderName: discovered.folderName,
      nameWasAdjusted: discovered.inferredSongName.changed,
      removedNameLabels: discovered.inferredSongName.removedLabels,
      nameSource: discovered.inferredSongName.source,
      folderPath: discovered.folderPath,
      start: timelinePosition,
      duration,
      end: timelinePosition + duration,
      files
    };
    songs.push(song);
    timelinePosition = song.end;
  }

  // Um nome desconhecido que se repete deixa de ser um caso isolado: a
  // auditoria cria uma pista própria e reserva Out somente para o que não
  // conseguiu identificar nem confirmar por recorrência.
  const recurringCandidates = new Map();
  for (const song of songs) {
    for (const file of song.files) {
      if (file.recognized || !file.candidateKey) continue;
      if (!recurringCandidates.has(file.candidateKey)) {
        recurringCandidates.set(file.candidateKey, { name: file.candidateName, count: 0 });
      }
      recurringCandidates.get(file.candidateKey).count += 1;
    }
  }
  for (const song of songs) {
    for (const file of song.files) {
      const candidate = recurringCandidates.get(file.candidateKey);
      if (!candidate || candidate.count < 2) continue;
      file.trackName = candidate.name;
      file.trackKey = file.candidateKey;
      file.recognized = true;
      file.inferredByRecurrence = true;
    }
  }

  // Dois arquivos da mesma música nunca podem ocupar a mesma pista e o
  // mesmo intervalo. Quando uma classificação se repete, abre outra pista
  // da mesma família em vez de sobrepor os itens no REAPER.
  for (const song of songs) {
    const reservedKeys = new Set(song.files.map((file) => file.trackKey));
    const usedKeys = new Set();
    for (const file of song.files) {
      if (!usedKeys.has(file.trackKey)) {
        usedKeys.add(file.trackKey);
        continue;
      }

      const baseName = file.trackName;
      let index = 2;
      let duplicateName = '';
      let duplicateKey = '';
      do {
        duplicateName = `${baseName} ${index}`;
        duplicateKey = file.trackKey.startsWith('custom:')
          ? `custom:${normalizeTrackKey(duplicateName)}`
          : normalizeTrackKey(duplicateName);
        index += 1;
      } while (reservedKeys.has(duplicateKey) || usedKeys.has(duplicateKey));

      file.trackName = duplicateName;
      file.trackKey = duplicateKey;
      file.separatedToPreventOverlap = true;
      reservedKeys.add(duplicateKey);
      usedKeys.add(duplicateKey);
    }
  }

  for (const song of songs) {
    for (const file of song.files) {
      if (!trackMap.has(file.trackKey)) {
        trackMap.set(file.trackKey, { name: file.trackName, key: file.trackKey, fileCount: 0, songNames: new Set(), unknownFileCount: 0 });
      }
      const track = trackMap.get(file.trackKey);
      track.fileCount += 1;
      track.songNames.add(song.name);
      if (!file.recognized) track.unknownFileCount += 1;
    }
  }

  const tracks = [...trackMap.values()]
    .map((track) => {
      const group = resolveCreateProjectTrackGroup(track.name);
      return { ...track, groupKey: group.key, groupName: group.name, songCount: track.songNames.size, songNames: [...track.songNames] };
    })
    .sort(compareTracks);
  const groups = createProjectTrackGroups(tracks);
  return {
    ok: true,
    folderPaths: uniqueFolders,
    totalFolders: uniqueFolders.length,
    validSongCount: songs.length,
    totalAudioFiles: discoveredAudioCount,
    totalIncludedFiles: songs.reduce((sum, song) => sum + song.files.length, 0),
    totalDuration: timelinePosition,
    tracks,
    groups,
    songs,
    emptyFolders,
    skippedFiles,
    unknownFileCount: tracks.reduce((sum, track) => sum + track.unknownFileCount, 0)
  };
}

function canonicalExistingTrackKey(trackName) {
  const classification = classifyCreateProjectTrack(`${String(trackName || '')}.wav`);
  return classification.recognized ? classification.key : normalizeTrackKey(trackName);
}

function groupKeyFromFolderName(folderName) {
  const key = normalizeTrackKey(folderName);
  const exact = CREATE_PROJECT_TRACK_GROUPS.find((group) => normalizeTrackKey(group.name) === key);
  if (exact) return exact.key;
  if (key === 'percussao' || key === 'percussivo') return 'percussivo';
  if (key === 'back-vocal' || key === 'back-vocais' || key === 'backing-vocals') return 'back-vocais';
  return '';
}


function suggestImportRemovals(names, { limit = 12 } = {}) {
 const groups = new Set(CREATE_PROJECT_TRACK_GROUPS.map(group => normalizeTrackKey(group.name)));
 return suggestRepeatedNames(names, { limit: Math.max(64, limit) })
   .filter(item => !groups.has(normalizeTrackKey(item.text)))
   .slice(0, limit);
}
function analyzeImport(folders) {
 const entries = new Map(folders.map(folder => [folder.path, folder.files]));
 const durations = new Map(folders.flatMap(folder => folder.files.map(file => [folder.path + '/' + file.name, file.duration])));
 const peaks = new Map(folders.flatMap(folder => folder.files.map(file => [folder.path + '/' + file.name, file.peakDb])));
 globalThis.fs = { promises: { readdir(folder) { return entries.get(folder).map(file => ({ name: file.name, isFile() { return true; } })); } } };
 return auditCreateProjectFolders({ folderPaths: folders.map(folder => folder.path), durationResolver: file => durations.get(file), peakResolver: file => peaks.get(file) });
}

"""#
}
