const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('hookUpdateCenter', {
  getState: () => ipcRenderer.invoke('get-state'),
  checkUpdates: () => ipcRenderer.invoke('check-updates'),
  downloadUpdate: (payload) => ipcRenderer.invoke('download-update', payload),
  getPreviousUpdates: () => ipcRenderer.invoke('get-previous-updates'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  checkHookCenterUpdate: () => ipcRenderer.invoke('check-hook-center-update'),
  installHookCenterUpdate: () => ipcRenderer.invoke('install-hook-center-update'),
  activateLicense: (payload) => ipcRenderer.invoke('activate-license', payload),
  checkLicenseStatus: () => ipcRenderer.invoke('check-license-status'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  openSupport: () => ipcRenderer.invoke('open-support'),
  getBridgeState: () => ipcRenderer.invoke('get-bridge-state'),
  restartBridge: () => ipcRenderer.invoke('restart-bridge'),
  getLyricsSettings: (slot) => ipcRenderer.invoke('get-lyrics-settings', slot),
  saveLyricsSettings: (payload) => ipcRenderer.invoke('save-lyrics-settings', payload),
  getTechnicalNoticeSettings: () => ipcRenderer.invoke('get-technical-notice-settings'),
  saveTechnicalNoticeSettings: (payload) => ipcRenderer.invoke('save-technical-notice-settings', payload),
  openLyricsWindow: (slot) => ipcRenderer.invoke('open-lyrics-window', slot),
  closeLyricsWindow: (slot) => ipcRenderer.invoke('close-lyrics-window', slot),
  getLyricsState: () => ipcRenderer.invoke('get-lyrics-state'),
  closeCurrentWindow: () => ipcRenderer.invoke('close-current-window'),
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (_event, data) => callback(data)),
  onLicenseStatus: (callback) => ipcRenderer.on('license-status', (_event, data) => callback(data)),
  onBridgeStatus: (callback) => ipcRenderer.on('bridge-status', (_event, data) => callback(data)),
  onUpdateError: (callback) => ipcRenderer.on('update-error', (_event, message) => callback(message)),
  onDownloadProgress: (callback) => ipcRenderer.on('download-progress', (_event, progress) => callback(progress)),
  onLyricsSettingsUpdated: (callback) => ipcRenderer.on('lyrics-settings-updated', (_event, data) => callback(data)),
  onTechnicalNoticeSettingsUpdated: (callback) => ipcRenderer.on('technical-notice-settings-updated', (_event, data) => callback(data))
});
