const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('hookUpdateCenter', {
  platform: process.platform,
  getState: () => ipcRenderer.invoke('get-state'),
  checkUpdates: () => ipcRenderer.invoke('check-updates'),
  downloadUpdate: (payload) => ipcRenderer.invoke('download-update', payload),
  cacheUpdatePackage: (payload) => ipcRenderer.invoke('cache-update-package', payload),
  removeCachedUpdatePackage: (payload) => ipcRenderer.invoke('remove-cached-update-package', payload),
  installCachedUpdatePackage: (payload) => ipcRenderer.invoke('install-cached-update-package', payload),
  getPreviousUpdates: () => ipcRenderer.invoke('get-previous-updates'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  checkHookCenterUpdate: () => ipcRenderer.invoke('check-hook-center-update'),
  installHookCenterUpdate: () => ipcRenderer.invoke('install-hook-center-update'),
  downloadHookCenterUpdate: () => ipcRenderer.invoke('download-hook-center-update'),
  installDownloadedHookCenterUpdate: () => ipcRenderer.invoke('install-downloaded-hook-center-update'),
  checkBridgeAppUpdate: () => ipcRenderer.invoke('check-bridge-app-update'),
  installBridgeAppUpdate: () => ipcRenderer.invoke('install-bridge-app-update'),
  activateLicense: (payload) => ipcRenderer.invoke('activate-license', payload),
  checkLicenseStatus: () => ipcRenderer.invoke('check-license-status'),
  getChatState: (afterId = 0) => ipcRenderer.invoke('chat-get-state', { afterId }),
  sendChatMessage: (payload) => ipcRenderer.invoke('chat-send-message', payload),
  setChatPinnedMessage: (payload) => ipcRenderer.invoke('chat-set-pinned-message', payload),
  deleteChatMessage: (payload) => ipcRenderer.invoke('chat-delete-message', payload),
  updateChatProfile: (payload) => ipcRenderer.invoke('chat-update-profile', payload),
  uploadChatAvatar: (payload) => ipcRenderer.invoke('chat-upload-avatar', payload),
  getDeviceName: () => ipcRenderer.invoke('get-device-name'),
  setDeviceName: (payload) => ipcRenderer.invoke('set-device-name', payload),
  loginLicenseDevices: (payload) => ipcRenderer.invoke('login-license-devices', payload),
  removeLicenseDevice: (payload) => ipcRenderer.invoke('remove-license-device', payload),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  openSupport: () => ipcRenderer.invoke('open-support'),
  selectHookRenameFolder: () => ipcRenderer.invoke('hook-rename-select-folder'),
  selectManyHookRenameFolders: () => ipcRenderer.invoke('hook-rename-select-many-folders'),
  previewHookRename: (payload) => ipcRenderer.invoke('hook-rename-preview', payload),
  runHookRename: (payload) => ipcRenderer.invoke('hook-rename-run', payload),
  getBridgeState: () => ipcRenderer.invoke('get-bridge-state'),
  restartBridge: () => ipcRenderer.invoke('restart-bridge'),
  selectBridgeNetwork: (payload) => ipcRenderer.invoke('select-bridge-network', payload),
  getLyricsSettings: (slot) => ipcRenderer.invoke('get-lyrics-settings', slot),
  saveLyricsSettings: (payload) => ipcRenderer.invoke('save-lyrics-settings', payload),
  getTechnicalNoticeSettings: () => ipcRenderer.invoke('get-technical-notice-settings'),
  saveTechnicalNoticeSettings: (payload) => ipcRenderer.invoke('save-technical-notice-settings', payload),
  sendRecadosNotice: (payload) => ipcRenderer.invoke('send-recados-notice', payload),
  cancelRecadosNotice: () => ipcRenderer.invoke('cancel-recados-notice'),
  setRecadosNoticePinned: (payload) => ipcRenderer.invoke('set-recados-notice-pinned', payload),
  exportLyricsBackup: () => ipcRenderer.invoke('export-lyrics-backup'),
  importLyricsBackup: () => ipcRenderer.invoke('import-lyrics-backup'),
  openLyricsWindow: (slot) => ipcRenderer.invoke('open-lyrics-window', slot),
  closeLyricsWindow: (slot) => ipcRenderer.invoke('close-lyrics-window', slot),
  getLyricsState: (slot) => ipcRenderer.invoke('get-lyrics-state', slot),
  closeCurrentWindow: () => ipcRenderer.invoke('close-current-window'),
  toggleCurrentWindowFullscreen: () => ipcRenderer.invoke('toggle-current-window-fullscreen'),
  getCurrentWindowBounds: () => ipcRenderer.invoke('get-current-window-bounds'),
  prepareCurrentWindowDrag: () => ipcRenderer.invoke('prepare-current-window-drag'),
  beginCurrentWindowCursorDrag: () => ipcRenderer.invoke('begin-current-window-cursor-drag'),
  moveCurrentWindowWithCursor: () => ipcRenderer.send('move-current-window-with-cursor'),
  endCurrentWindowCursorDrag: () => ipcRenderer.send('end-current-window-cursor-drag'),
  moveCurrentWindow: (payload) => ipcRenderer.send('move-current-window', payload),
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (_event, data) => callback(data)),
  onLicenseStatus: (callback) => ipcRenderer.on('license-status', (_event, data) => callback(data)),
  onBridgeStatus: (callback) => ipcRenderer.on('bridge-status', (_event, data) => callback(data)),
  onUpdateError: (callback) => ipcRenderer.on('update-error', (_event, message) => callback(message)),
  onDownloadProgress: (callback) => ipcRenderer.on('download-progress', (_event, progress) => callback(progress)),
  onHookRenameProgress: (callback) => ipcRenderer.on('hook-rename-progress', (_event, progress) => callback(progress)),
  onLyricsSettingsUpdated: (callback) => ipcRenderer.on('lyrics-settings-updated', (_event, data) => callback(data)),
  onTechnicalNoticeSettingsUpdated: (callback) => ipcRenderer.on('technical-notice-settings-updated', (_event, data) => callback(data)),
  onLyricsWindowsStateUpdated: (callback) => ipcRenderer.on('lyrics-windows-state-updated', (_event, data) => callback(data))
});
