const { contextBridge, ipcRenderer } = require('electron');

const systemVersion = typeof process.getSystemVersion === 'function'
  ? process.getSystemVersion()
  : '';

contextBridge.exposeInMainWorld('hookUpdateCenter', {
  platform: process.platform,
  osRelease: systemVersion,
  getState: () => ipcRenderer.invoke('get-state'),
  checkUpdates: () => ipcRenderer.invoke('check-updates'),
  downloadUpdate: (payload) => ipcRenderer.invoke('download-update', payload),
  cacheUpdatePackage: (payload) => ipcRenderer.invoke('cache-update-package', payload),
  removeCachedUpdatePackage: (payload) => ipcRenderer.invoke('remove-cached-update-package', payload),
  installCachedUpdatePackage: (payload) => ipcRenderer.invoke('install-cached-update-package', payload),
  getPreviousUpdates: () => ipcRenderer.invoke('get-previous-updates'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  checkHookCenterUpdate: () => ipcRenderer.invoke('check-hook-center-update'),
  installHookCenterUpdate: () => ipcRenderer.invoke('install-hook-center-update'),
  downloadHookCenterUpdate: () => ipcRenderer.invoke('download-hook-center-update'),
  installDownloadedHookCenterUpdate: () => ipcRenderer.invoke('install-downloaded-hook-center-update'),
  checkBridgeAppUpdate: () => ipcRenderer.invoke('check-bridge-app-update'),
  installBridgeAppUpdate: () => ipcRenderer.invoke('install-bridge-app-update'),
  activateLicense: (payload) => ipcRenderer.invoke('activate-license', payload),
  checkLicenseStatus: () => ipcRenderer.invoke('check-license-status'),
  getChatState: (afterId = 0) => ipcRenderer.invoke('chat-get-state', { afterId }),
  sendChatMessage: (payload) => ipcRenderer.invoke('chat-send-message', payload),
  setChatPinnedMessage: (payload) => ipcRenderer.invoke('chat-set-pinned-message', payload),
  editChatMessage: (payload) => ipcRenderer.invoke('chat-edit-message', payload),
  deleteChatMessage: (payload) => ipcRenderer.invoke('chat-delete-message', payload),
  updateChatProfile: (payload) => ipcRenderer.invoke('chat-update-profile', payload),
  uploadChatAvatar: (payload) => ipcRenderer.invoke('chat-upload-avatar', payload),
  getHookTutorials: () => ipcRenderer.invoke('get-hook-tutorials'),
  updateChatAdminSettings: (payload) => ipcRenderer.invoke('chat-admin-update-settings', payload),
  clearChatAsAdmin: (payload) => ipcRenderer.invoke('chat-admin-clear', payload),
  unlockChatAdmin: (payload) => ipcRenderer.invoke('chat-admin-unlock', payload),
  saveChatReleaseNotes: (payload) => ipcRenderer.invoke('chat-admin-save-release-notes', payload),
  publishUpdateFromHookCenter: (payload) => ipcRenderer.invoke('chat-admin-publish-update', payload),
  getDeviceName: () => ipcRenderer.invoke('get-device-name'),
  setDeviceName: (payload) => ipcRenderer.invoke('set-device-name', payload),
  loginLicenseDevices: (payload) => ipcRenderer.invoke('login-license-devices', payload),
  removeLicenseDevice: (payload) => ipcRenderer.invoke('remove-license-device', payload),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  openSupport: () => ipcRenderer.invoke('open-support'),
  selectManyHookRenameFolders: () => ipcRenderer.invoke('hook-rename-select-many-folders'),
  previewHookRename: (payload) => ipcRenderer.invoke('hook-rename-preview', payload),
  runHookRename: (payload) => ipcRenderer.invoke('hook-rename-run', payload),
  selectCreateProjectDestination: () => ipcRenderer.invoke('create-project-select-destination'),
  selectCreateProjectFolders: () => ipcRenderer.invoke('create-project-select-folders'),
  auditCreateProject: (payload) => ipcRenderer.invoke('create-project-audit', payload),
  runCreateProject: (payload) => ipcRenderer.invoke('create-project-run', payload),
  openCreateProject: (payload) => ipcRenderer.invoke('create-project-open', payload),
  selectAddProjectFile: () => ipcRenderer.invoke('add-project-select-project'),
  selectAddProjectFolders: () => ipcRenderer.invoke('add-project-select-folders'),
  auditAddProject: (payload) => ipcRenderer.invoke('add-project-audit', payload),
  runAddProject: (payload) => ipcRenderer.invoke('add-project-run', payload),
  openAddProject: (payload) => ipcRenderer.invoke('add-project-open', payload),
  getDirectCableState: () => ipcRenderer.invoke('direct-cable-get-state'),
  configureDirectCable: (payload) => ipcRenderer.invoke('direct-cable-configure', payload),
  disconnectDirectCable: (payload) => ipcRenderer.invoke('direct-cable-disconnect', payload),
  restartDirectCable: (payload) => ipcRenderer.invoke('direct-cable-restart', payload),
  getMacShowModeState: () => ipcRenderer.invoke('mac-show-mode-get-state'),
  setMacShowMode: (payload) => ipcRenderer.invoke('mac-show-mode-set', payload),
  getHookMidiState: () => ipcRenderer.invoke('hook-midi-get-state'),
  createHookMidiPort: (payload) => ipcRenderer.invoke('hook-midi-create', payload),
  removeHookMidiPort: (payload) => ipcRenderer.invoke('hook-midi-remove', payload),
  openHookMidiComponents: () => ipcRenderer.invoke('hook-midi-open-components'),
  setHookMidiMtcOutput: (payload) => ipcRenderer.invoke('hook-midi-set-mtc-output', payload),
  setHookMidiMtcSwitchSource: (payload) => ipcRenderer.invoke('hook-midi-mtc-switch-source', payload),
  getHookMarkerState: () => ipcRenderer.invoke('hook-marker-get-state'),
  saveHookMarkerSettings: (payload) => ipcRenderer.invoke('hook-marker-save-settings', payload),
  exportHookMarkerGrandMa2: (payload) => ipcRenderer.invoke('hook-marker-export-grandma2', payload),
  exportHookMarkerResolume: (payload) => ipcRenderer.invoke('hook-marker-export-resolume', payload),
  testHookMarkerResolume: (payload) => ipcRenderer.invoke('hook-marker-test-resolume', payload),
  startHookMarkerResolume: (payload) => ipcRenderer.invoke('hook-marker-start-resolume', payload),
  stopHookMarkerResolume: () => ipcRenderer.invoke('hook-marker-stop-resolume'),
  getHookMarkerRuntimeState: () => ipcRenderer.invoke('hook-marker-get-runtime-state'),
  selectCopyProjectFolder: (mode) => ipcRenderer.invoke('copy-project-select-folder', { mode }),
  getCopyProjectState: () => ipcRenderer.invoke('copy-project-get-state'),
  refreshCopyProjectDevices: () => ipcRenderer.invoke('copy-project-refresh-devices'),
  startCopyProjectReceive: (payload) => ipcRenderer.invoke('copy-project-start-receive', payload),
  stopCopyProjectReceive: () => ipcRenderer.invoke('copy-project-stop-receive'),
  sendCopyProject: (payload) => ipcRenderer.invoke('copy-project-send', payload),
  startCopyProjectShare: (payload) => ipcRenderer.invoke('copy-project-start-share', payload),
  stopCopyProjectShare: () => ipcRenderer.invoke('copy-project-stop-share'),
  cancelCopyProject: () => ipcRenderer.invoke('copy-project-cancel'),
  openCopyProjectDestination: () => ipcRenderer.invoke('copy-project-open-destination'),
  getBridgeState: () => ipcRenderer.invoke('get-bridge-state'),
  restartBridge: () => ipcRenderer.invoke('restart-bridge'),
  selectBridgeNetwork: (payload) => ipcRenderer.invoke('select-bridge-network', payload),
  getLyricsSettings: (slot) => ipcRenderer.invoke('get-lyrics-settings', slot),
  saveLyricsSettings: (payload) => ipcRenderer.invoke('save-lyrics-settings', payload),
  getTechnicalNoticeSettings: () => ipcRenderer.invoke('get-technical-notice-settings'),
  saveTechnicalNoticeSettings: (payload) => ipcRenderer.invoke('save-technical-notice-settings', payload),
  sendRecadosNotice: (payload) => ipcRenderer.invoke('send-recados-notice', payload),
  cancelRecadosNotice: () => ipcRenderer.invoke('cancel-recados-notice'),
  setRecadosNoticePinned: (payload) => ipcRenderer.invoke('set-recados-notice-pinned', payload),
  exportLyricsBackup: () => ipcRenderer.invoke('export-lyrics-backup'),
  importLyricsBackup: () => ipcRenderer.invoke('import-lyrics-backup'),
  openLyricsWindow: (slot) => ipcRenderer.invoke('open-lyrics-window', slot),
  closeLyricsWindow: (slot) => ipcRenderer.invoke('close-lyrics-window', slot),
  getLyricsState: (slot) => ipcRenderer.invoke('get-lyrics-state', slot),
  closeCurrentWindow: () => ipcRenderer.invoke('close-current-window'),
  toggleCurrentWindowFullscreen: () => ipcRenderer.invoke('toggle-current-window-fullscreen'),
  getCurrentWindowBounds: () => ipcRenderer.invoke('get-current-window-bounds'),
  prepareCurrentWindowDrag: () => ipcRenderer.invoke('prepare-current-window-drag'),
  beginCurrentWindowCursorDrag: () => ipcRenderer.invoke('begin-current-window-cursor-drag'),
  moveCurrentWindowWithCursor: () => ipcRenderer.send('move-current-window-with-cursor'),
  endCurrentWindowCursorDrag: () => ipcRenderer.send('end-current-window-cursor-drag'),
  moveCurrentWindow: (payload) => ipcRenderer.send('move-current-window', payload),
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (_event, data) => callback(data)),
  onLicenseStatus: (callback) => ipcRenderer.on('license-status', (_event, data) => callback(data)),
  onBridgeStatus: (callback) => ipcRenderer.on('bridge-status', (_event, data) => callback(data)),
  onDirectCableStatus: (callback) => ipcRenderer.on('direct-cable-status', (_event, data) => callback(data)),
  onUpdateError: (callback) => ipcRenderer.on('update-error', (_event, message) => callback(message)),
  onDownloadProgress: (callback) => ipcRenderer.on('download-progress', (_event, progress) => callback(progress)),
  onHookRenameProgress: (callback) => ipcRenderer.on('hook-rename-progress', (_event, progress) => callback(progress)),
  onCreateProjectProgress: (callback) => ipcRenderer.on('create-project-progress', (_event, progress) => callback(progress)),
  onAddProjectProgress: (callback) => ipcRenderer.on('add-project-progress', (_event, progress) => callback(progress)),
  onCopyProjectState: (callback) => ipcRenderer.on('copy-project-state', (_event, state) => callback(state)),
  onHookMidiMtcSwitch: (callback) => ipcRenderer.on('hook-midi-mtc-switch', (_event, state) => callback(state)),
  onHookMarkerRuntimeState: (callback) => ipcRenderer.on('hook-marker-runtime-state', (_event, state) => callback(state)),
  onLyricsSettingsUpdated: (callback) => ipcRenderer.on('lyrics-settings-updated', (_event, data) => callback(data)),
  onTechnicalNoticeSettingsUpdated: (callback) => ipcRenderer.on('technical-notice-settings-updated', (_event, data) => callback(data)),
  onLyricsWindowsStateUpdated: (callback) => ipcRenderer.on('lyrics-windows-state-updated', (_event, data) => callback(data))
});
